[package]
name = "pcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.16"
pest = "2.2.1"
state = "0.5.3"
serde = { version = "1.0.143", features = ["derive"] }
ron = "0.7.1"